### ISSUE TITLE
testing for scalaide and ensime support

### ISSUE THREAD

**Issue by fommil** [bkirwi/applicative-syntax#1]
FYI, if you wanted to know if this works in the presentation compiler you could try out https://github.com/ensime/pcplod

My guess is that it will break the PC all over the place... there are an insane number of hacks to workaround `for` comprehensions.

**Comment by bkirwi** [comment]
Sorry, not sure why I missed this -- I'll have a look!

(Anecdotally, IntelliJ IDEA doesn't complain about the for comprehensions in this project... though it does complain about the `@applicative` annotation, since it doesn't correspond to anything actually in scope.)
